export const LOADING_START = 'LOADING_START';

export const CREATE_EXCHANGE = 'CREATE_EXCHANGE';
export const DELETE_EXCHANGE = 'DELETE_EXCHANGE';

/* charts */
export const LOAD_CHART_SUCCESS = 'LOAD_CHART_SUCCESS';
export const LOAD_CHART_RISK_SUCCESS = 'LOAD_CHART_RISK_SUCCESS';

/* balances */
export const LOAD_BALANCES_SUCCESS = 'LOAD_BALANCES_SUCCESS';

/* coins */
export const LOAD_COINS_FRONT_SUCCESS = 'LOAD_COINS_FRONT_SUCCESS';