export const LOADING_START = 'LOADING_START'

export const CREATE_EXCHANGE = 'CREATE_EXCHANGE'
export const UPDATE_EXCHANGE = 'UPDATE_EXCHANGE'
export const DELETE_EXCHANGE = 'DELETE_EXCHANGE'

/* charts */
export const LOAD_CHART_SUCCESS = 'LOAD_CHART_SUCCESS'
export const LOAD_CHART_RISK_SUCCESS = 'LOAD_CHART_RISK_SUCCESS'
export const CLEAR_CHARTS = 'CLEAR_CHARTS'
export const SET_CHART_LOADED = 'SET_CHART_LOADED'
export const SET_STATUS_TEXT = 'SET_STATUS_TEXT'
export const CHART_ERROR = 'CHART_ERROR'
export const BALANCE_ERROR = 'BALANCE_ERROR'

export const PORTFOLIO_CALCULATION_BEGIN = 'PORTFOLIO_CALCULATION_BEGIN'
export const PORTFOLIO_CALCULATION_FINISH = 'PORTFOLIO_CALCULATION_FINISH'
export const PORTFOLIO_CALCULATION_ERROR = 'PORTFOLIO_CALCULATION_ERROR'
export const PORTFOLIO_CALCULATION_UPDATE = 'PORTFOLIO_CALCULATION_UPDATE'

/* balances */
export const LOAD_BALANCES_SUCCESS = 'LOAD_BALANCES_SUCCESS'
export const CLEAR_BALANCES = 'CLEAR_BALANCES'
export const CALC_BALANCES_SUCCESS = 'CALC_BALANCES_SUCCESS'
export const CALC_BALANCES_START = 'CALC_BALANCES_START'
export const CALC_BALANCES_ERROR = 'CALC_BALANCES_ERROR'
export const CALC_BALANCES_FETCH = 'CALC_BALANCES_FETCH'
export const CALC_BALANCES_ADD = 'CALC_BALANCES_ADD'
/* coins */
export const LOAD_COINS_FRONT_SUCCESS = 'LOAD_COINS_FRONT_SUCCESS'

/* Extension */
export const GET_EXTENSION_VERSION_SUCCESS = 'GET_EXTENSION_VERSION_SUCCESS'

/* CopyCrypto */
export const GET_INVITE_REQUESTED = 'GET_INVITE_REQUESTED'
export const GET_INVITE_REJECTED = 'GET_INVITE_REJECTED'
export const GET_INVITE_SUCCESS = 'GET_INVITE_SUCCESS'

/* User */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const SET_DARK_THEME = 'SET_DARK_THEME'

/* Admin */
export const ADMIN_ON = 'ADMIN_ON'
export const ADMIN_OFF = 'ADMIN_OFF'

/* Portfolio */
export const CREATE_PORTFOLIO = 'CREATE_PORTFOLIO'
export const ADD_PORTFOLIO = 'ADD_PORTFOLIO'
export const ADD_USER_PORTFOLIO = 'ADD_USER_PORTFOLIO'
export const ADD_USER_PORTFOLIOS = 'ADD_USER_PORTFOLIOS'
export const ADD_ADDRESS_TO_PORTFOLIO = 'ADD_ADDRESS_TO_PORTFOLIO'
export const UPDATE_CALCULATIONS = 'UPDATE_CALCULATIONS'
export const LOAD_PORTFOLIO_CALCULATIONS = 'LOAD_PORTFOLIO_CALCULATIONS'
export const BEGIN_FETCHING_PORTFOLIO = 'BEGIN_FETCHING_PORTFOLIO'

export const CLEAR_PORTFOLIOS = 'CLEAR_PORTFOLIOS'
export const BEGIN_USER_PORTFOLIOS_FETCHING = 'BEGIN_USER_PORTFOLIOS_FETCHING'
export const NO_USER_PORTFOLIOS_FOUND = 'NO_USER_PORTFOLIOS_FOUND'
