export const LOADING_START = 'LOADING_START'

export const CREATE_EXCHANGE = 'CREATE_EXCHANGE'
export const UPDATE_EXCHANGE = 'UPDATE_EXCHANGE'
export const DELETE_EXCHANGE = 'DELETE_EXCHANGE'

/* charts */
export const LOAD_CHART_SUCCESS = 'LOAD_CHART_SUCCESS'
export const LOAD_CHART_RISK_SUCCESS = 'LOAD_CHART_RISK_SUCCESS'
export const CLEAR_CHARTS = 'CLEAR_CHARTS'
export const SET_CHART_LOADED = 'SET_CHART_LOADED'
export const SET_STATUS_TEXT = 'SET_STATUS_TEXT'
export const CHART_ERROR = 'CHART_ERROR'
export const BALANCE_ERROR = 'BALANCE_ERROR'

/* balances */
export const LOAD_BALANCES_SUCCESS = 'LOAD_BALANCES_SUCCESS'
export const CLEAR_BALANCES = 'CLEAR_BALANCES'

/* coins */
export const LOAD_COINS_FRONT_SUCCESS = 'LOAD_COINS_FRONT_SUCCESS'

/* Extension */
export const GET_EXTENSION_VERSION_SUCCESS = 'GET_EXTENSION_VERSION_SUCCESS'

/* CopyCrypto */
export const GET_INVITE_REQUESTED = 'GET_INVITE_REQUESTED'
export const GET_INVITE_REJECTED = 'GET_INVITE_REJECTED'
export const GET_INVITE_SUCCESS = 'GET_INVITE_SUCCESS'

/* User */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const SET_DARK_THEME = 'SET_DARK_THEME'

/* Admin */
export const ADMIN_ON = 'ADMIN_ON'
export const ADMIN_OFF = 'ADMIN_OFF'

/* Portfolio */
export const CREATE_PORTFOLIO = 'CREATE_PORTFOLIO'
export const ADD_PORTFOLIO = 'ADD_PORTFOLIO'
export const ADD_USER_PORTFOLIO = 'ADD_USER_PORTFOLIO'
export const ADD_USER_PORTFOLIOS = 'ADD_USER_PORTFOLIOS'
export const CLEAR_PORTFOLIOS = 'CLEAR_PORTFOLIOS'
