export const LOADING_START = 'LOADING_START';

export const CREATE_EXCHANGE = 'CREATE_EXCHANGE';
export const DELETE_EXCHANGE = 'DELETE_EXCHANGE';

/* charts */
export const LOAD_CHART_SUCCESS = 'LOAD_CHART_SUCCESS';
export const LOAD_CHART_RISK_SUCCESS = 'LOAD_CHART_RISK_SUCCESS';
export const CLEAR_CHARTS = 'CLEAR_CHARTS';
export const SET_CHART_LOADED = 'SET_CHART_LOADED';

/* balances */
export const LOAD_BALANCES_SUCCESS = 'LOAD_BALANCES_SUCCESS';
export const CLEAR_BALANCES = 'CLEAR_BALANCES';

/* coins */
export const LOAD_COINS_FRONT_SUCCESS = 'LOAD_COINS_FRONT_SUCCESS';

/* Extension */
export const GET_EXTENSION_VERSION_SUCCESS = 'GET_EXTENSION_VERSION_SUCCESS';
